### ISSUE TITLE
Sass error when running gulp

### ISSUE THREAD

**Issue by jessamynsmith** [jbutko/AngularJS-Boilerplate#10]
I get the following error when I try to run gulp:

AngularJS-Boilerplate$ gulp
[22:41:19] Using gulpfile ~/Development/codementor/AngularJS-Boilerplate/gulpfile.js
[22:41:19] Starting 'browser-sync'...
[22:41:19] Finished 'browser-sync' after 186 ms
[22:41:19] Starting 'sass'...
[22:41:19] 'sass' errored after 57 ms
[22:41:19] Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (/Users/jessamyn/Development/codementor/AngularJS-Boilerplate/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:22:11)
    at Object.<anonymous> (/Users/jessamyn/Development/codementor/AngularJS-Boilerplate/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:188:23)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/jessamyn/Development/codementor/AngularJS-Boilerplate/node_modules/gulp-sass/index.js:3:17)
    at Module._compile (module.js:430:26)

**Comment by jbutko** [comment]
Try to remove gulp-sass from package.json, then issue npm install, after that install gulp-sass via npm install gulp-sass --save-dev
This should solve the problem.
